[tool.ruff]
# Enable the pycodestyle (`E`) and Pyflakes (`F`) rules by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
lint.select = ["E", "F", "TID252", "NPY201", "W", "PLE", "PLW", "B007", "SIM115", "SIM108", "SIM101", "SIM102",
    "SIM103", "SIM105", "SIM107", "SIM109", "SIM110", "SIM112", "SIM114", "SIM116", "SIM117", "SIM118", "SIM201",
    "SIM202"]
lint.ignore = ["E501", "SIM113", "SIM300"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
lint.fixable = ["ALL"]
lint.unfixable = []

# Specify github format
output-format = "github"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]
lint.per-file-ignores = {'__init__.py' = ['F822'], 'PyRoute/Calculation/TradeMPCalculation.py' = ['PLW0602', 'PLW0603']}

# Same as Black.
line-length = 120

# Allow unused variables when underscore-prefixed.
lint.dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.9
target-version = "py39"
